app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('user/<int:user_id>?success=<success>', views.user, name='user'),
    path('user/<int:user_id>', views.user, name='user'),
    path('company/<int:company_id>', views.company, name='company'),
    path('projects', views.projects, name='projects'),
    # path(r'<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path(r'<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path(r'<int:question_id>/vote/', views.vote, name='vote'),
]

bolacha/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('app.urls')),
]

app/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=500)


class User(models.Model):
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=500)


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    area = models.CharField(max_length=100)
    tema = models.CharField(max_length=100)
    subtema = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.CharField(max_length=500)

    def currencies(self):
        return Currency.objects.filter(project_id=self.pk)

    def equipments(self):
        return Equipment.objects.filter(project_id=self.pk)


class Resource(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Currency(Resource):
    amount = models.DecimalField(max_digits=20, decimal_places=2)


class Equipment(Resource):
    name = models.CharField(max_length=100)


class Transaction(models.Model):
    cost = models.DecimalField(max_digits=20, decimal_places=2)
    seller = models.CharField(max_length=100)


class Product(models.Model):
    name = models.CharField(max_length=100)
    cost = models.DecimalField(max_digits=20, decimal_places=2)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)

app/forms.py
from django import forms


class ProjectForm(forms.Form):
    title = forms.CharField(label='Nome do projeto', max_length=100)
    description = forms.CharField(label='Descrição', max_length=400)
    area = forms.CharField(label='Área', max_length=100)
    tema = forms.CharField(label='Tema', max_length=100)
    subtema = forms.CharField(label='Subtema', max_length=100)
    currency = forms.DecimalField(label='Precisa de (R$)', decimal_places=2, max_digits=20, min_value=0)
    equipment = forms.CharField(label='Equipamentos')
    image = forms.CharField(label='Imagem', max_length=500)


class ProjectSearchForm(forms.Form):
    area = forms.CharField(label='Área', required=False)
    tema = forms.CharField(label='Tema', max_length=100, required=False)
    subtema = forms.CharField(label='Subtema', max_length=100, required=False)

app/views.py
from django.views import generic
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import User, Project, Currency, Equipment, Company
from .forms import ProjectForm, ProjectSearchForm
from urllib import parse


class IndexView(generic.base.TemplateView):
    template_name = 'app/index.html'


def user(request, user_id):
    u = get_object_or_404(User, pk=user_id)

    if request.method == 'POST':
        print(request.POST)
        form = ProjectForm(request.POST)
        success = form.is_valid()

        if success:
            proj = Project.objects.create(title=form.cleaned_data['title'], description=form.cleaned_data['description'],
                                          area=form.cleaned_data['area'], tema=form.cleaned_data['tema'],
                                          subtema=form.cleaned_data['subtema'], image=form.cleaned_data['image'],
                                          user_id=user_id)
            if form.cleaned_data['currency'] != 0:
                Currency.objects.create(
                    amount=form.cleaned_data['currency'], project_id=proj.pk)
            for equip in form.cleaned_data['equipment'].split(','):
                equip = equip.strip()
                if equip != '':
                    Equipment.objects.create(name=equip, project_id=proj.pk)

        return redirect(reverse(f'app:user', args=[user_id]) + '?success=' + str(success).lower())

    success = request.GET.get('success', None)

    context = {
        'user': u,
        'projects': Project.objects.filter(user_id=user_id),
        'form': ProjectForm(),
        'submitted': success is not None,
        'success': success and (success.lower() == 'true'),
        'logged_in': True,
    }
    return render(request, 'app/user.html', context)


def projects(request):
    context = {
        'projects': Project.objects.all(),
    }
    return render(request, 'app/projects.html', context)


def company(request, company_id):
    c = get_object_or_404(Company, pk=company_id)
    projs = []

    if request.method == 'POST':
        print(request.POST)
        form = ProjectSearchForm(request.POST)
        if not form.is_valid():
            print(form.errors)
        return redirect(reverse(f'app:company', args=[company_id]) + '?' + parse.urlencode({
            'area': form.cleaned_data['area'],
            'tema': form.cleaned_data['tema'],
            'subtema': form.cleaned_data['subtema']}))

    area = request.GET.get('area', None)
    tema = request.GET.get('tema', None)
    subtema = request.GET.get('subtema', None)

    if {area, tema, subtema} != {None}:
        projs = Project.objects.filter(
            area__contains=area or '', tema__contains=tema or '', subtema__contains=subtema or '')
        no_matches = len(projs) == 0
    else:
        projs = []
        no_matches = False

    context = {
        'company': c,
        'projects': projs,
        'form': ProjectSearchForm(),
        'no_matches': no_matches,
        'logged_in': True,
        'show_projects': len(projs) > 0,
    }
    return render(request, 'app/company.html', context)

app/templates/app/company.html
{% extends "base.html" %}

{% block title %} {{company.name}} {% endblock %}

{% block nav-start %}
<div class="item" style="width: 17em;"></div>
{% endblock %}


<!-- Following Menu -->
{% block afternav %}
<div class="ui sidebar inverted vertical menu visible" style="width: 19%;">
  <a class="item" href="{% url 'app:company' company.pk %}" style="background-color: #333;">
    <img class="ui avatar image" src="{{company.image}}" style="width: 50px; height: auto"> <b>{{company.name}}</b>
  </a>
  <a class="item">Perfil</a>
  <a class="item">Histórico</a>
  <a class="item">Configurações</a>
  <a class="item">Ajuda</a>
</div>
{% endblock %}

{% block content %}

<div style="margin-right: 25%; margin-left:15%; margin-top: 5%;">

  <h2 class="ui header">
    Apoie o Fundo
  </h2>

  <div class="ui equal width grid">
    <div class="column" style="font-size: 1.2em; margin: auto; text-align: center;">
      Incentive projetos na universidade doando a nosso fundo. Ao doar, sua empresa concorre a uma série de benefícios.
    </div>
    <div class="column">
      <div class="ui statistic">
        <div class="label">
          NOSSO PATRIMÔNIO
        </div>
        <div class="value">
          R$ 350 milhões
        </div>
      </div>
    </div>
    <div class="column" style="font-size: 1.2em; margin: auto;">
      <div class="ui list">
        <div class="item">
          <i class="right triangle icon"></i>
          Seja parceiro da USP
        </div>
        <div class="item">
          <i class="right triangle icon"></i>
          Promova a inovação tecnológica
        </div>
        <div class="item">
          <i class="right triangle icon"></i>
          Lei do bem - receba uma série de incentivos fiscais
        </div>
      </div>
    </div>
    <br>

    <div class="row centered">
      <div class="column six wide">
        <div class="ui left action input" style="width: 100%; font-size: 1.2em">
          <a class="ui teal labeled icon button" style="font-size: 1.2em; padding: .2em">
            <i class="dollar sign icon"></i>
            Contribua com
          </a>
          <input type="text" value="R$ 10.000,00">
        </div>
      </div>
    </div>
  </div>


  <h2 class="ui dividing header" style="margin-top: 5em;">
    Encontre seu projeto
  </h2>

  <form class="ui large form" method="post" action="{% url 'app:company' company.pk %}">
    {% csrf_token %}
    <div class="three fields">
      <div class="field">
        <label> {{ form.area.label }} </label>
        {{ form.area }}
      </div>
      <div class="field">
        <label> {{ form.tema.label }} </label>
        {{ form.tema }}
      </div>
      <div class="field">
        <label> {{ form.subtema.label }} </label>
        {{ form.subtema }}
      </div>
    </div>
    <input type="submit" class="eleven wide ui fluid large submit button" value="Buscar">
    <input type="hidden" name="next" value="{{ next }}">
  </form>

  {% if no_matches %}
  <div class="ui negative message">
    <i class="close icon"></i>
    <div class="header">
      Nenhum projeto encontrado
    </div>
  </div>
  {% endif %}


  {% if show_projects %}

  <div style="display: flex; align-content: flex-start; align-items: flex-start; flex-flow: row wrap;">
    {% for p in projects %}
    <div class="ui card" style="flex: 0 0 29%; margin: 1em;">
      <div class="image">
        <img src="{{p.image}}">
      </div>
      <div class="content">
        <div class="header">{{p.title}}</div>
        <div class="meta">
          <span class="category">{{p.area}} | {{p.tema}} | {{p.subtema}}</span>
        </div>
        <div class="description">
          <p></p>
        </div>
      </div>
      <div class="extra content">
        <p>{{p.description}}</p>
        <b>Precisa de:</b>
        <ul>
          {% for c in p.currencies %}
          <li>R$ {{c.amount}}</li>
          {%endfor%}
          {% for e in p.equipments %}
          <li> {{e.name}} </li>
          {%endfor%}
        </ul>
        <div class="right floated author">
          <a href="{% url 'app:user' p.user.pk %}">
            <img class="ui avatar image" src="{{p.user.image}}"> {{p.user.name}}
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}
</div>
{% endblock %}

app/templates/app/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Home{% endblock %}

{% block scripts %}{% endblock %}
{% block nav %}{% endblock %}


{% block precontent %}
<div class="ui inverted vertical masthead center aligned segment" style="min-height: 0;">

  <div class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <a class="toc item">
        <i class="sidebar icon"></i>
      </a>
      <a class="active item" href="/">Home</a>
      <a class="item">Saiba Mais</a>
      <a class="item" href="{% url 'app:projects' %}">Veja um Projeto</a>
      <a class="item" href="{% url 'app:user' 1 %}">Submeta um Projeto</a>
      <a class="item" href="{% url 'app:company' 1 %}">Contribua</a>
      <a class="item">Denúncias</a>
      <div class="right item">
        <a class="ui inverted button" href="{% url 'login' %}">Login</a>
        <a class="ui inverted button">Signup</a>
      </div>
    </div>
  </div>

  <div class="ui text container">
    <img src="{% static 'app/logo-dark.png' %}" style="width: 50%; padding: 8% 0">
  </div>

</div>

{% endblock %}

{% block content %}
<div class="ui vertical stripe segment" style="margin-right: 30%; margin-left: 30%; padding-top: 3%">
  <div class="ui equal width stackable internally celled grid">
    <div class="aligned row">
      <div class="column">
        <h3 style="text-align: center;">Para faculdades</h3>
        <p>Submeta projetos de pesquisa/extensão/ensino que podem ser financiadas por empresas. </p>
        <p> Mantenha a transparência quanto ao desenvolvimento de suas atividades. </p>
        <div class="ui list">
          <div class="item" style="font-size: 1.2em">
            <i class="right triangle icon"></i>
            Financiamento
          </div>
          <div class="item" style="font-size: 1.2em">
            <i class="right triangle icon"></i>
            Fortalecimento do tripé ensino/extensão/pesquisa
          </div>
          <div class="item" style="font-size: 1.2em">
            <i class="right triangle icon"></i>
            Renda independente de impostos e fora de orçamentos
          </div>
          <div style="display: flex; align-items: center; justify-content: center; margin-top: 1em;">
            <a class="ui primary button" href="{% url 'app:user' 1 %}">Envie seu projeto</a>
          </div>
        </div>
      </div>
      <div class="column">
        <h3 style="text-align: center;">Para empresas</h3>
        <p> Mostre que você apoia a pesquisa e o ensino na USP! </p>
        <p> Veja como você pode apoiar nosso fundo, ou ajudar nossos projetos diretamente. </p>
        <div class="ui list">
          <div class="item" style="font-size: 1.2em">
            <i class="right triangle icon"></i>
            Selo parceiro da USP
          </div>
          <div class="item" style="font-size: 1.2em">
            <i class="right triangle icon"></i>
            Contato direto com nossos alunos e professores
          </div>
          <div class="item" style="font-size: 1.2em">
            <i class="right triangle icon"></i>
            Inovação tecnológica
          </div>
          <div class="item" style="font-size: 1.2em">
            <i class="right triangle icon"></i>
            Lei do bem
          </div>
          <div style="display: flex; align-items: center; justify-content: center; margin-top: 1em;">
            <div class="ui vertical buttons">
              <a class="ui primary button" href="{% url 'app:company' 1 %}">Procure um projeto</a>
              <a class="ui primary button" href="{% url 'app:company' 1 %}">Ajude o fundo</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="ui grid container" style="width: 80%; margin-top: -4em;">
  <div class="sixteen wide column" style="text-align: center; margin-bottom: 3em">
    <h1 class="ui header">Nossos Maiores Parceiros</h1>
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/pagseguro.png' %}">
    <img style="position: absolute; top: -.5em; right: -.5em; width: 4em; height: auto;" src="{% static 'app/badges/M.png' %}">
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/bradesco.svg' %}">
    <img style="position: absolute; top: -.5em; right: 4em; width: 4em; height: auto;" src="{% static 'app/badges/100.png' %}">
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/vtex.svg' %}">
    <img style="position: absolute; top: -.5em; right: 2em; width: 4em; height: auto;" src="{% static 'app/badges/M.png' %}">
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/tfg.svg' %}">
    <img style="position: absolute; top: -.5em; right: 2em; width: 4em; height: auto;" src="{% static 'app/badges/10.png' %}">
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/taqtile.png' %}">
    <img style="position: absolute; top: 0em; right: 1em; width: 4em; height: auto;" src="{% static 'app/badges/100.png' %}">
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/intelie.png' %}">
    <img style="position: absolute; top: 0em; right: -1em; width: 4em; height: auto;" src="{% static 'app/badges/10.png' %}">
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/hash.png' %}">
    <img style="position: absolute; top: 0em; right: 0em; width: 4em; height: auto;" src="{% static 'app/badges/100.png' %}">
  </div>
  <div class="four wide column" style="padding: 2em;">
    <img style="width: 100%;" src="{% static 'app/companies/udemy.png' %}">
    <img style="position: absolute; top: -1em; right: 2em; width: 4em; height: auto;" src="{% static 'app/badges/M.png' %}">
  </div>
</div>
{% endblock %}

app/templates/app/projects.html
{% extends "base.html" %}

{% block title %} Projetos {% endblock %}

{% block content %}

<div style="margin-right: 25%; margin-left:10%; margin-top: 5%;">

  <h2 class="ui dividing header" style="margin-top: 3em">
    Acompanhe os projetos
  </h2>

  <div style="display: flex; align-content: flex-start; align-items: flex-start; flex-flow: row wrap;">
    {% for p in projects %}
    <div class="ui card" style="flex: 0 0 29%; margin: 1em;">
      <div class="image">
        <img src="{{p.image}}">
      </div>
      <div class="content">
        <div class="header">{{p.title}}</div>
        <div class="meta">
          <span class="category">{{p.area}} | {{p.tema}} | {{p.subtema}}</span>
        </div>
        <div class="description">
          <p></p>
        </div>
      </div>
      <div class="extra content">
        <p>{{p.description}}</p>
        <b>Precisa de:</b>
        <ul>
          {% for c in p.currencies %}
          <li>R$ {{c.amount}}</li>
          {%endfor%}
          {% for e in p.equipments %}
          <li> {{e.name}} </li>
          {%endfor%}
        </ul>
        <div class="right floated author">
          <a href="{% url 'app:user' p.user.pk %}">
            <img class="ui avatar image" src="{{p.user.image}}"> {{p.user.name}}
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/app/user.html
{% extends "base.html" %}

{% block title %} {{user.name}} {% endblock %}

{% block nav-start %}
<div class="item" style="width: 17.5em;"></div>
{% endblock %}

{% block afternav %}
<div class="ui sidebar inverted vertical menu visible" style="width: 20%;">
  <a class="item" href="{% url 'app:user' user.pk %}" style="background-color: #333;">
    <img class="ui avatar image" src="{{user.image}}" style="width: 50px; height: auto"> <b>{{user.name}}</b>
  </a>
  <a class="item">Perfil</a>
  <a class="item">Histórico</a>
  <a class="item">Configurações</a>
  <a class="item">Ajuda</a>
</div>
{% endblock %}

{% block content %}

<div style="margin-right: 25%; margin-left:10%; margin-top: 5%;">

  <h2 class="ui header">
    Envie seu projeto
  </h2>

  <form class="ui large form" method="post" action="{% url 'app:user' user.pk %}}">
    {% csrf_token %}
    <div class="ui stacked">
      <div class="field">
        <label> {{ form.title.label }} </label>
        <div class="ui input">
          {{ form.title }}
        </div>
      </div>
      <div class="three fields">
        <div class="field">
          <label> {{ form.area.label }} </label>
          {{ form.area }}
        </div>
        <div class="field">
          <label> {{ form.tema.label }} </label>
          {{ form.tema }}
        </div>
        <div class="field">
          <label> {{ form.subtema.label }} </label>
          {{ form.subtema }}
        </div>
      </div>
      <div class="fields">
        <div class="three wide field">
          <label> {{ form.currency.label }} </label>
          {{ form.currency }}
        </div>
        <div class="five wide field">
          <label> {{ form.equipment.label }} </label>
          {{ form.equipment }}
        </div>
        <div class="eight wide field">
          <label> {{ form.description.label }} </label>
          {{ form.description }}
        </div>
      </div>
      <div class="fields">
        <div class="five wide field">
          <label> {{ form.image.label }} </label>
          {{ form.image }}
        </div>
        <input type="submit" class="eleven wide ui fluid large submit button" value="Enviar">
      </div>
      <input type="hidden" name="next" value="{{ next }}">
    </div>
  </form>

  {% if submitted %}
  {% if success %}
  <div class="ui positive message">
    <i class="close icon"></i>
    <div class="header">
      Projeto enviado
    </div>
  </div>
  {%else%}
  <div class="ui negative message">
    <i class="close icon"></i>
    <div class="header">
      Dados inválidos
    </div>
  </div>
  {% endif %}
  {% endif %}


  <h2 class="ui dividing header" style="margin-top: 3em">
    Acompanhe seus outros projetos
  </h2>

  <div style="display: flex; align-content: flex-start; align-items: flex-start; flex-flow: row wrap;">
    {% for p in projects %}
    <div class="ui card" style="flex: 0 0 29%; margin: 1em;">
      <div class="image">
        <img src="{{p.image}}">
      </div>
      <div class="content">
        <div class="header">{{p.title}}</div>
        <div class="meta">
          <span class="category">{{p.area}} | {{p.tema}} | {{p.subtema}}</span>
        </div>
        <div class="description">
          <p></p>
        </div>
      </div>
      <div class="extra content">
        <p>{{p.description}}</p>
        <b>Precisa de:</b>
        <ul>
          {% for c in p.currencies %}
          <li>R$ {{c.amount}}</li>
          {%endfor%}
          {% for e in p.equipments %}
          <li> {{e.name}} </li>
          {%endfor%}
        </ul>
        <div class="right floated author">
          <a href="{% url 'app:user' p.user.pk %}">
            <img class="ui avatar image" src="{{p.user.image}}"> {{p.user.name}}
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <link rel="shortcut icon" type="image/png" href="/static/app/favicon.png"/>

  <!-- Site Properties -->
  <title>{% block title %}{% endblock %} - Gaia</title>
  <link rel="stylesheet" type="text/css" href="https://cdn.staticaly.com/gh/Semantic-Org/Semantic-UI/deb275d2/dist/semantic.min.css">

  <style type="text/css">
    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }

    .masthead .logo.item img {
      margin-right: 1em;
    }

    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }

    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }

    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }

    .ui.vertical.stripe h3 {
      font-size: 2em;
    }

    .ui.vertical.stripe .button+h3,
    .ui.vertical.stripe p+h3 {
      margin-top: 3em;
    }

    .ui.vertical.stripe .floated.image {
      clear: both;
    }

    .ui.vertical.stripe p {
      font-size: 1.33em;
    }

    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }

    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }

      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }

      .secondary.pointing.menu .toc.item {
        display: block;
      }

      .masthead.segment {
        min-height: 350px;
      }

      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }

      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }
  </style>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdn.staticaly.com/gh/Semantic-Org/Semantic-UI/deb275d2/dist/semantic.min.js"></script>
  {% block scripts %}
  <script>
    $(document)
      .ready(function () {

        // create sidebar and attach to menu open
        $('.ui.sidebar')
          .sidebar('attach events', '.toc.item');

      });
  </script>
  {% endblock %}
</head>

<body>

  {% block nav %}
  <div class="ui large top fixed menu">
    {% block nav-start %}{% endblock %}
    <div class="item">
      <img src="{% static 'app/logo-main.png' %}" style="height: 2em; width: auto;">
    </div>
    <div class="ui container">
      <a class="item" href="/">
        Home
      </a>
      <a class="item">Saiba Mais</a>
      <a class="item" href="{% url 'app:projects' %}">Veja um Projeto</a>
      <a class="item" href="{% url 'app:user' 1 %}">Submeta um Projeto</a>
      <a class="item" href="{% url 'app:company' 1 %}">Contribua</a>
      <a class="item">Denúncias</a>
      <div class="right menu">
        {% if logged_in %}
        <div class="item">
          <a class="ui button" href="#">Log out</a>
        </div>
        {% else %}
        <div class="item">
          <a class="ui button" href="{% url 'login' %}">Login</a>
        </div>
        <div class="item">
          <a class="ui primary button">Signup</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  {% endblock %}

  {% block afternav %}{% endblock %}


  <!-- Page Contents -->
  <div class="pusher">
    {% block precontent %}{% endblock %}

    {% block content %}{% endblock %}

    {% comment %}
    <div class="ui vertical stripe segment">
      <div class="ui equal width stackable internally celled grid">
        <div class="center aligned row">
          <div class="column">
            <h3>"What a Company"</h3>
            <p>That is what they all say about us</p>
          </div>
          <div class="column">
            <h3>"I shouldn't have gone with their competitor."</h3>
            <p>
              <b>Nan</b> Chief Fun Officer Acme Toys
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="ui vertical stripe segment">
      <div class="ui text container">
        <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
        <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing
          nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and
          worth your attention.</p>
        <a class="ui large button">Read More</a>
        <h4 class="ui horizontal header divider">
          <a href="#">Case Studies</a>
        </h4>
        <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
        <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true.
          It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
        <a class="ui large button">I'm Still Quite Interested</a>
      </div>
    </div>


    <div class="ui inverted vertical footer segment">
      <div class="ui container">
        <div class="ui stackable inverted divided equal height stackable grid">
          <div class="three wide column">
            <h4 class="ui inverted header">About</h4>
            <div class="ui inverted link list">
              <a href="#" class="item">Sitemap</a>
              <a href="#" class="item">Contact Us</a>
              <a href="#" class="item">Religious Ceremonies</a>
              <a href="#" class="item">Gazebo Plans</a>
            </div>
          </div>
          <div class="three wide column">
            <h4 class="ui inverted header">Services</h4>
            <div class="ui inverted link list">
              <a href="#" class="item">Banana Pre-Order</a>
              <a href="#" class="item">DNA FAQ</a>
              <a href="#" class="item">How To Access</a>
              <a href="#" class="item">Favorite X-Men</a>
            </div>
          </div>
          <div class="seven wide column">
            <h4 class="ui inverted header">Footer Header</h4>
            <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
          </div>
        </div>
      </div>
    </div> {% endcomment %}
  </div>

</body>

</html>